dist: bionic
language: python

services:
  - postgresql

python:
  - '2.7'

addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.4

env:
  - GEOKEY='>=1.6,<1.7' DJANGO='>=1.11,<1.12' DEPLOY=0
  - GEOKEY='>=1.7,<1.8' DJANGO='>=1.11,<1.12' DEPLOY=1

install:
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo apt-get install binutils ffmpeg 
  - sudo apt-get -yq install libgdal-dev python-gdal
  - gdal-config --version
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal

before_script:
  - psql template1 postgres -c 'create extension hstore;'
  - psql -c 'create database geokey;' -U postgres
  - psql -U postgres -d geokey -c 'create extension postgis;'
  - pip install rsa==4.5
  - pip install "regex<2022.1.18"
  - pip install geokey$GEOKEY
  - pip install django$DJANGO
  - python -c "import django; print('DJANGO %s ' % django.get_version())"
  - python -c "from geokey.version import get_version; print('GEOKEY %s' % get_version())"
  - pip install -r travis_ci/requirements.txt
  - pip install -e .
  - pip install gdal==`gdal-config --version`
  - python travis_ci/manage.py migrate

script:
  - coverage run --source=geokey_dataimports travis_ci/manage.py test geokey_dataimports

after_success:
  - coveralls

deploy:
  provider: pypi
  user: excites
  password:
    secure: XW5YgDb645Tnue/rl5xH/+P8gzq+ssKV746wEXAfCMZTJGvLXOR2uc1Or3q2j/fbmOrDSxOECJjCcfbsP5v8IrybtZ5ux014ebgqHjBaDrPN1n3ooTnnV3e5MNiZ2Vc+TL/Voypq/G7g384pt6QlOdBt51S/0kUzWvlHBRDQcMWcs8sU5WsBVpB/MBzuC2AmSfrPa0fZp5ua7tqLUdpt5eH9xt9kxWAqpE5WdSZMHeZF2kMyIFIK7S+Vy5IboU70yrc700WU2IAFSuenJSj3QqBhGzmDfovvSHCanMn9BKR1rFOFBOZJLTE8Vh5nlqkwlxPPLH+ytp6DQvEC6yKV6SwGwm7Bdgwl+ZJw9I2m5x43kck5oh9mjrfXrJyvl2TtwFV1ShDqX3NLJakzohQhq79TmutkZLzjhE3FUVsHOFtqogSEqGKK3fx9UTsKiDqrkBV7jETAcy66u65xrXuKwwNmQOVZhitzKy9kilwJ7y+QR9ScLybjxI3HPp0bWrDHmmM2YDAMKLzvn7Fo+ffDDttXIfLxVIyog6WG9HE+WFrfjdXf6hZ8FhCmqIv7K9/RdWMxcgQk6KR4DMabOhgDKbMdyEOiQTXSi9r3SfzXclBbajGXsgbEWlAOcdkMuJ0Yhbta4jehGIPQqxUTMFqaeZG9WS1aUuUNB2RANpdLJBk=
  on:
    tags: true
    branch: master
    condition: $DEPLOY = 1
